# Generated by Django 4.1.1 on 2022-09-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_type_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='correct_question',
            new_name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='userAnswer',
            field=models.CharField(default='Empty Answer', max_length=100),
        ),
    ]
